---
- name: CPE212-Automating Server Management Final Project
  hosts: all
  become: true

  vars:
    docker_image_name: "webapp-image"
    docker_container_name: "webapp-container"

  tasks:
    - name: Start and enable docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Open Port in the firewall
      ufw:
        rule: allow
        port: 8080
        proto: tcp

    - name: Copy website files to Ubuntu and Centos servers
      copy:
        src: ./  
        dest: /tmp/website
        remote_src: no

    - name: Build Docker image 
      command: docker build -t "{{ docker_image_name }}" .
      args:
        chdir: /tmp/website

    - name: Run Docker container
      command: docker run -d --name "{{ docker_container_name }}" -p {{ docker_port }}:80 "{{ docker_image_name }}"


